### ISSUE TITLE
Update project files to .NET 10

### ISSUE THREAD

**Issue by nickna** [knnlabs/Conduit#566]
## Overview

Update all .NET project files (.csproj) to target .NET 10 framework and update Target Framework Monikers (TFM).

## Scope

Update 17 .NET projects currently targeting `net9.0` to `net10.0`:

### Core Projects
- `ConduitLLM.Core/ConduitLLM.Core.csproj`
- `ConduitLLM.Configuration/ConduitLLM.Configuration.csproj`
- `ConduitLLM.Security/ConduitLLM.Security.csproj`
- `ConduitLLM.Providers/ConduitLLM.Providers.csproj`

### API Projects
- `ConduitLLM.Http/ConduitLLM.Http.csproj` (Web API)
- `ConduitLLM.Admin/ConduitLLM.Admin.csproj` (Admin API)

### Test Projects
- `ConduitLLM.Tests/ConduitLLM.Tests.csproj`
- `ConduitLLM.Http.Tests/ConduitLLM.Http.Tests.csproj`
- `ConduitLLM.Admin.Tests/ConduitLLM.Admin.Tests.csproj`
- `ConduitLLM.IntegrationTests/ConduitLLM.IntegrationTests.csproj`

### Other Projects
- `ConduitLLM.Examples/ConduitLLM.Examples.csproj`
- `ConduitLLM.Benchmarks/ConduitLLM.Benchmarks.csproj`

### Tool Projects
- `tools/XmlDocumentationChecker/XmlDocumentationCoverageChecker.csproj`
- `tools/SignalRBackplaneTest/SignalRBackplaneTest.csproj`
- `Clients/Node/scripts/GenerateOpenApiSpecs/GenerateOpenApiSpecs.csproj`

### Legacy/Archive Projects
- Archive projects in `archive/` directory (if needed)

### 1. Update Target Framework Monikers
Change all instances of:
```xml
<TargetFramework>net9.0</TargetFramework>
```

To:
```xml
<TargetFramework>net10.0</TargetFramework>
```

### 2. Verify Project Properties
Ensure these properties remain consistent:
- `<ImplicitUsings>enable</ImplicitUsings>`
- `<Nullable>enable</Nullable>`
- SDK versions (`Microsoft.NET.Sdk`, `Microsoft.NET.Sdk.Web`)

### 3. Update Global.json (if exists)
Check for and update any global.json files that might pin SDK versions.

### 4. Validate Build Configuration
- Ensure all configurations (Debug/Release) work with net10.0
- Verify Docker build configurations work with .NET 10

## Prerequisites

- [ ] .NET 10 SDK installed
- [ ] Issues #564 (Redis startup) and #565 (async patterns) resolved
- [ ] All tests passing on .NET 9

### Build Validation
- [ ] `dotnet build` succeeds for all projects
- [ ] `dotnet build --configuration Release` succeeds
- [ ] Solution builds successfully: `dotnet build Conduit.sln`

### Runtime Validation  
- [ ] All projects start successfully
- [ ] Basic functionality smoke testing
- [ ] Docker containers build with .NET 10

### Standard Web Project (e.g., ConduitLLM.Http.csproj)
```xml
<!-- BEFORE -->
<TargetFramework>net9.0</TargetFramework>

<!-- AFTER -->
<TargetFramework>net10.0</TargetFramework>
```

### Standard Library Project (e.g., ConduitLLM.Core.csproj)
```xml
<!-- BEFORE -->  
<TargetFramework>net9.0</TargetFramework>

<!-- AFTER -->
<TargetFramework>net10.0</TargetFramework>
```

## Definition of Done

- [ ] All 17 .NET projects target `net10.0`
- [ ] `dotnet build` succeeds for entire solution
- [ ] No compilation errors or warnings introduced
- [ ] All project references work correctly
- [ ] Docker builds work with .NET 10
- [ ] CI/CD pipeline updated to use .NET 10 SDK

## Follow-up Issues

This issue should be followed by:
- Package updates (#567)
- Breaking change fixes (#568)
- Comprehensive testing (#569)

## Related Issues

Part of Epic #563 (.NET 10 Upgrade)
